# -*- coding: utf-8 -*-
"""Data importing and annoting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zp-_pD9VCUTtbyCmtsh_a1wLf0ycPgDr
"""

#Importing Libraries
import sys
import scanpy as sc
import anndata
import pandas as pd
import numpy as np
import os
import gc

#Importing Libraries
import seaborn as sns
from matplotlib import pyplot as plt
import matplotlib as mpl

#Loading the data
sp_data_folder = '/content/drive/MyDrive/breastcancer'

#reading the visium data
adata = sc.read_visium(sp_data_folder, count_file='filtered_feature_bc_matrix.h5', load_images=True)

#Making adata variable names as unique
adata.var_names_make_unique()

#Checking the AnnData object
adata

#adata data shape
adata.X.shape

#Adata spatial shape checking
adata.obsm['spatial'].shape

#Adata observation obs making unique
adata.obs_names_make_unique()

#Checking the adata obs that loaded from the csv
adata.obs

#Show those genes that yield the highest fraction of counts in each single cell, across all cells.
sc.pl.highest_expr_genes(adata, n_top=20,)