# -*- coding: utf-8 -*-
"""Lib Installation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zp-_pD9VCUTtbyCmtsh_a1wLf0ycPgDr
"""

!pip install scanpy

!pip install anndata